### ISSUE TITLE
Put player safe down when flight time is over

### ISSUE THREAD

**Issue by zackern** [CaptnSisko/FlyTime#1]
When the flight time is over it should put the player on the ground like it does when you log out instead of just turn the flight off so the player can be damaged.
It should also do this when you are in the air and do /fly.

**Comment by CaptnSisko** [comment]
Thanks for the suggestion. I'll work on it this weekend if I get a chance.

**Comment by zackern** [comment]
Ok. Sounds good :+1:

**Comment by CaptnSisko** [comment]
Done! Be sure to delete your old config file to be sure the new options are present.
