### ISSUE TITLE
Request: Change to how flight time is set.

### ISSUE THREAD

**Issue by connorhsm** [CaptnSisko/FlyTime#3]
Instead of a blanket setting of how long a player can fly, what if players were issued with flight time?
Such as /flytime set/give/take/reset playerName amount

**Comment by CaptnSisko** [comment]
This could certainly be done, but at the moment I am rather busy and unlikely to find the time to add this in the near future. You are welcome to submit a pull request or write proprietary code for your server using this as a template since the project is open source.
